/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed": "#f0dbff",
        "surface": "#131313",
        "on-secondary-container": "#d6a9ff",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#ddb7ff",
        "secondary-container": "#6f00be",
        "on-secondary-fixed-variant": "#6900b3",
        "on-primary-container": "#ede0ff",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "on-secondary": "#490080",
        "error": "#ffb4ab",
        "on-tertiary-container": "#76ffc2",
        "on-primary": "#3f008e",
        "on-primary-fixed": "#25005a",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#313030",
        "surface-tint": "#d2bbff",
        "on-surface-variant": "#ccc3d8",
        "on-error": "#690005",
        "on-background": "#e5e2e1",
        "primary-fixed": "#eaddff",
        "tertiary-fixed": "#6ffbbe",
        "secondary": "#ddb7ff",
        "on-tertiary": "#003824",
        "tertiary-container": "#007650",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#93000a",
        "outline-variant": "#4a4455",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary": "#732ee4",
        "on-tertiary-fixed": "#002113",
        "surface-bright": "#3a3939",
        "on-secondary-fixed": "#2c0051",
        "primary-container": "#7c3aed",
        "tertiary": "#4edea3",
        "surface-dim": "#131313",
        "primary-fixed-dim": "#d2bbff",
        "primary": "#d2bbff",
        "outline": "#958da1"
      },
      fontFamily: {
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
